<?php
/**
 * Project: PHP Light Framework
 *
 * @author      Michal Szewczyk <ms@msworks.pl>
 * @copyright   Michal Szewczyk
 * @license     MIT
 */
declare(strict_types=1);

use MS\LightFramework\GeoIP\Timezone;
use PHPUnit\Framework\TestCase;


class TimezoneTest extends TestCase
{

    public function setUp()
    {
    }

    public function testGet()
    {
        $this->assertSame(Timezone::get(), 'Europe/Warsaw');
        $this->assertSame(Timezone::get('US', 'AL'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'AK'), 'America/Anchorage');
        $this->assertSame(Timezone::get('US', 'AZ'), 'America/Phoenix');
        $this->assertSame(Timezone::get('US', 'AR'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'CA'), 'America/Los_Angeles');
        $this->assertSame(Timezone::get('US', 'CO'), 'America/Denver');
        $this->assertSame(Timezone::get('US', 'CT'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'DE'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'DC'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'FL'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'GA'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'HI'), 'Pacific/Honolulu');
        $this->assertSame(Timezone::get('US', 'ID'), 'America/Denver');
        $this->assertSame(Timezone::get('US', 'IL'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'IN'), 'America/Indianapolis');
        $this->assertSame(Timezone::get('US', 'IA'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'KS'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'KY'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'LA'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'ME'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'MD'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'MA'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'MI'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'MN'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'MS'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'MO'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'MT'), 'America/Denver');
        $this->assertSame(Timezone::get('US', 'NE'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'NV'), 'America/Los_Angeles');
        $this->assertSame(Timezone::get('US', 'NH'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'NJ'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'NM'), 'America/Denver');
        $this->assertSame(Timezone::get('US', 'NY'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'NC'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'ND'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'OH'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'OK'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'OR'), 'America/Los_Angeles');
        $this->assertSame(Timezone::get('US', 'PA'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'RI'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'SC'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'SD'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'TN'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'TX'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'UT'), 'America/Denver');
        $this->assertSame(Timezone::get('US', 'VT'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'VA'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'WA'), 'America/Los_Angeles');
        $this->assertSame(Timezone::get('US', 'WV'), 'America/New_York');
        $this->assertSame(Timezone::get('US', 'WI'), 'America/Chicago');
        $this->assertSame(Timezone::get('US', 'WY'), 'America/Denver');

        $this->assertSame(Timezone::get('CA', 'AB'), 'America/Edmonton');
        $this->assertSame(Timezone::get('CA', 'BC'), 'America/Vancouver');
        $this->assertSame(Timezone::get('CA', 'MB'), 'America/Winnipeg');
        $this->assertSame(Timezone::get('CA', 'NB'), 'America/Halifax');
        $this->assertSame(Timezone::get('CA', 'NL'), 'America/St_Johns');
        $this->assertSame(Timezone::get('CA', 'NT'), 'America/Yellowknife');
        $this->assertSame(Timezone::get('CA', 'NS'), 'America/Halifax');
        $this->assertSame(Timezone::get('CA', 'NU'), 'America/Rankin_Inlet');
        $this->assertSame(Timezone::get('CA', 'ON'), 'America/Rainy_River');
        $this->assertSame(Timezone::get('CA', 'PE'), 'America/Halifax');
        $this->assertSame(Timezone::get('CA', 'QC'), 'America/Montreal');
        $this->assertSame(Timezone::get('CA', 'SK'), 'America/Regina');
        $this->assertSame(Timezone::get('CA', 'YT'), 'America/Whitehorse');

        $this->assertSame(Timezone::get('AU', '01'), 'Australia/Canberra');
        $this->assertSame(Timezone::get('AU', '02'), 'Australia/NSW');
        $this->assertSame(Timezone::get('AU', '03'), 'Australia/North');
        $this->assertSame(Timezone::get('AU', '04'), 'Australia/Queensland');
        $this->assertSame(Timezone::get('AU', '05'), 'Australia/South');
        $this->assertSame(Timezone::get('AU', '06'), 'Australia/Tasmania');
        $this->assertSame(Timezone::get('AU', '07'), 'Australia/Victoria');
        $this->assertSame(Timezone::get('AU', '08'), 'Australia/West');

        $this->assertSame(Timezone::get('AS'), 'US/Samoa');
        $this->assertSame(Timezone::get('CI'), 'Africa/Abidjan');
        $this->assertSame(Timezone::get('GH'), 'Africa/Accra');
        $this->assertSame(Timezone::get('DZ'), 'Africa/Algiers');
        $this->assertSame(Timezone::get('ER'), 'Africa/Asmera');
        $this->assertSame(Timezone::get('ML'), 'Africa/Bamako');
        $this->assertSame(Timezone::get('CF'), 'Africa/Bangui');
        $this->assertSame(Timezone::get('GM'), 'Africa/Banjul');
        $this->assertSame(Timezone::get('GW'), 'Africa/Bissau');
        $this->assertSame(Timezone::get('CG'), 'Africa/Brazzaville');
        $this->assertSame(Timezone::get('BI'), 'Africa/Bujumbura');
        $this->assertSame(Timezone::get('EG'), 'Africa/Cairo');
        $this->assertSame(Timezone::get('MA'), 'Africa/Casablanca');
        $this->assertSame(Timezone::get('GN'), 'Africa/Conakry');
        $this->assertSame(Timezone::get('SN'), 'Africa/Dakar');
        $this->assertSame(Timezone::get('DJ'), 'Africa/Djibouti');
        $this->assertSame(Timezone::get('SL'), 'Africa/Freetown');
        $this->assertSame(Timezone::get('BW'), 'Africa/Gaborone');
        $this->assertSame(Timezone::get('ZW'), 'Africa/Harare');
        $this->assertSame(Timezone::get('ZA'), 'Africa/Johannesburg');
        $this->assertSame(Timezone::get('UG'), 'Africa/Kampala');
        $this->assertSame(Timezone::get('SD'), 'Africa/Khartoum');
        $this->assertSame(Timezone::get('RW'), 'Africa/Kigali');
        $this->assertSame(Timezone::get('NG'), 'Africa/Lagos');
        $this->assertSame(Timezone::get('GA'), 'Africa/Libreville');
        $this->assertSame(Timezone::get('TG'), 'Africa/Lome');
        $this->assertSame(Timezone::get('AO'), 'Africa/Luanda');
        $this->assertSame(Timezone::get('ZM'), 'Africa/Lusaka');
        $this->assertSame(Timezone::get('GQ'), 'Africa/Malabo');
        $this->assertSame(Timezone::get('MZ'), 'Africa/Maputo');
        $this->assertSame(Timezone::get('LS'), 'Africa/Maseru');
        $this->assertSame(Timezone::get('SZ'), 'Africa/Mbabane');
        $this->assertSame(Timezone::get('SO'), 'Africa/Mogadishu');
        $this->assertSame(Timezone::get('LR'), 'Africa/Monrovia');
        $this->assertSame(Timezone::get('KE'), 'Africa/Nairobi');
        $this->assertSame(Timezone::get('TD'), 'Africa/Ndjamena');
        $this->assertSame(Timezone::get('NE'), 'Africa/Niamey');
        $this->assertSame(Timezone::get('MR'), 'Africa/Nouakchott');
        $this->assertSame(Timezone::get('BF'), 'Africa/Ouagadougou');
        $this->assertSame(Timezone::get('ST'), 'Africa/Sao_Tome');
        $this->assertSame(Timezone::get('LY'), 'Africa/Tripoli');
        $this->assertSame(Timezone::get('TN'), 'Africa/Tunis');
        $this->assertSame(Timezone::get('AI'), 'America/Anguilla');
        $this->assertSame(Timezone::get('AG'), 'America/Antigua');
        $this->assertSame(Timezone::get('AW'), 'America/Aruba');
        $this->assertSame(Timezone::get('BB'), 'America/Barbados');
        $this->assertSame(Timezone::get('BZ'), 'America/Belize');
        $this->assertSame(Timezone::get('CO'), 'America/Bogota');
        $this->assertSame(Timezone::get('VE'), 'America/Caracas');
        $this->assertSame(Timezone::get('KY'), 'America/Cayman');
        $this->assertSame(Timezone::get('CR'), 'America/Costa_Rica');
        $this->assertSame(Timezone::get('DM'), 'America/Dominica');
        $this->assertSame(Timezone::get('SV'), 'America/El_Salvador');
        $this->assertSame(Timezone::get('GD'), 'America/Grenada');
        $this->assertSame(Timezone::get('FR'), 'Europe/Paris');
        $this->assertSame(Timezone::get('GP'), 'America/Guadeloupe');
        $this->assertSame(Timezone::get('GT'), 'America/Guatemala');
        $this->assertSame(Timezone::get('GY'), 'America/Guyana');
        $this->assertSame(Timezone::get('CU'), 'America/Havana');
        $this->assertSame(Timezone::get('JM'), 'America/Jamaica');
        $this->assertSame(Timezone::get('BO'), 'America/La_Paz');
        $this->assertSame(Timezone::get('PE'), 'America/Lima');
        $this->assertSame(Timezone::get('NI'), 'America/Managua');
        $this->assertSame(Timezone::get('MQ'), 'America/Martinique');
        $this->assertSame(Timezone::get('UY'), 'America/Montevideo');
        $this->assertSame(Timezone::get('MS'), 'America/Montserrat');
        $this->assertSame(Timezone::get('BS'), 'America/Nassau');
        $this->assertSame(Timezone::get('PA'), 'America/Panama');
        $this->assertSame(Timezone::get('SR'), 'America/Paramaribo');
        $this->assertSame(Timezone::get('PR'), 'America/Puerto_Rico');
        $this->assertSame(Timezone::get('KN'), 'America/St_Kitts');
        $this->assertSame(Timezone::get('LC'), 'America/St_Lucia');
        $this->assertSame(Timezone::get('VC'), 'America/St_Vincent');
        $this->assertSame(Timezone::get('HN'), 'America/Tegucigalpa');
        $this->assertSame(Timezone::get('YE'), 'Asia/Aden');
        $this->assertSame(Timezone::get('JO'), 'Asia/Amman');
        $this->assertSame(Timezone::get('TM'), 'Asia/Ashgabat');
        $this->assertSame(Timezone::get('IQ'), 'Asia/Baghdad');
        $this->assertSame(Timezone::get('BH'), 'Asia/Bahrain');
        $this->assertSame(Timezone::get('AZ'), 'Asia/Baku');
        $this->assertSame(Timezone::get('TH'), 'Asia/Bangkok');
        $this->assertSame(Timezone::get('LB'), 'Asia/Beirut');
        $this->assertSame(Timezone::get('KG'), 'Asia/Bishkek');
        $this->assertSame(Timezone::get('BN'), 'Asia/Brunei');
        $this->assertSame(Timezone::get('IN'), 'Asia/Calcutta');
        $this->assertSame(Timezone::get('MN'), 'Asia/Choibalsan');
        $this->assertSame(Timezone::get('LK'), 'Asia/Colombo');
        $this->assertSame(Timezone::get('BD'), 'Asia/Dhaka');
        $this->assertSame(Timezone::get('AE'), 'Asia/Dubai');
        $this->assertSame(Timezone::get('TJ'), 'Asia/Dushanbe');
        $this->assertSame(Timezone::get('HK'), 'Asia/Hong_Kong');
        $this->assertSame(Timezone::get('TR'), 'Asia/Istanbul');
        $this->assertSame(Timezone::get('IL'), 'Asia/Jerusalem');
        $this->assertSame(Timezone::get('AF'), 'Asia/Kabul');
        $this->assertSame(Timezone::get('PK'), 'Asia/Karachi');
        $this->assertSame(Timezone::get('NP'), 'Asia/Katmandu');
        $this->assertSame(Timezone::get('KW'), 'Asia/Kuwait');
        $this->assertSame(Timezone::get('MO'), 'Asia/Macao');
        $this->assertSame(Timezone::get('PH'), 'Asia/Manila');
        $this->assertSame(Timezone::get('OM'), 'Asia/Muscat');
        $this->assertSame(Timezone::get('CY'), 'Asia/Nicosia');
        $this->assertSame(Timezone::get('KP'), 'Asia/Pyongyang');
        $this->assertSame(Timezone::get('QA'), 'Asia/Qatar');
        $this->assertSame(Timezone::get('MM'), 'Asia/Rangoon');
        $this->assertSame(Timezone::get('SA'), 'Asia/Riyadh');
        $this->assertSame(Timezone::get('KR'), 'Asia/Seoul');
        $this->assertSame(Timezone::get('SG'), 'Asia/Singapore');
        $this->assertSame(Timezone::get('TW'), 'Asia/Taipei');
        $this->assertSame(Timezone::get('GE'), 'Asia/Tbilisi');
        $this->assertSame(Timezone::get('BT'), 'Asia/Thimphu');
        $this->assertSame(Timezone::get('JP'), 'Asia/Tokyo');
        $this->assertSame(Timezone::get('LA'), 'Asia/Vientiane');
        $this->assertSame(Timezone::get('AM'), 'Asia/Yerevan');
        $this->assertSame(Timezone::get('BM'), 'Atlantic/Bermuda');
        $this->assertSame(Timezone::get('CV'), 'Atlantic/Cape_Verde');
        $this->assertSame(Timezone::get('FO'), 'Atlantic/Faeroe');
        $this->assertSame(Timezone::get('IS'), 'Atlantic/Reykjavik');
        $this->assertSame(Timezone::get('GS'), 'Atlantic/South_Georgia');
        $this->assertSame(Timezone::get('SH'), 'Atlantic/St_Helena');
        $this->assertSame(Timezone::get('CL'), 'Chile/Continental');
        $this->assertSame(Timezone::get('NL'), 'Europe/Amsterdam');
        $this->assertSame(Timezone::get('AD'), 'Europe/Andorra');
        $this->assertSame(Timezone::get('GR'), 'Europe/Athens');
        $this->assertSame(Timezone::get('YU'), 'Europe/Belgrade');
        $this->assertSame(Timezone::get('DE'), 'Europe/Berlin');
        $this->assertSame(Timezone::get('SK'), 'Europe/Bratislava');
        $this->assertSame(Timezone::get('BE'), 'Europe/Brussels');
        $this->assertSame(Timezone::get('RO'), 'Europe/Bucharest');
        $this->assertSame(Timezone::get('HU'), 'Europe/Budapest');
        $this->assertSame(Timezone::get('DK'), 'Europe/Copenhagen');
        $this->assertSame(Timezone::get('IE'), 'Europe/Dublin');
        $this->assertSame(Timezone::get('GI'), 'Europe/Gibraltar');
        $this->assertSame(Timezone::get('FI'), 'Europe/Helsinki');
        $this->assertSame(Timezone::get('SI'), 'Europe/Ljubljana');
        $this->assertSame(Timezone::get('GB'), 'Europe/London');
        $this->assertSame(Timezone::get('LU'), 'Europe/Luxembourg');
        $this->assertSame(Timezone::get('MT'), 'Europe/Malta');
        $this->assertSame(Timezone::get('BY'), 'Europe/Minsk');
        $this->assertSame(Timezone::get('MC'), 'Europe/Monaco');
        $this->assertSame(Timezone::get('NO'), 'Europe/Oslo');
        $this->assertSame(Timezone::get('CZ'), 'Europe/Prague');
        $this->assertSame(Timezone::get('LV'), 'Europe/Riga');
        $this->assertSame(Timezone::get('IT'), 'Europe/Rome');
        $this->assertSame(Timezone::get('SM'), 'Europe/San_Marino');
        $this->assertSame(Timezone::get('BA'), 'Europe/Sarajevo');
        $this->assertSame(Timezone::get('MK'), 'Europe/Skopje');
        $this->assertSame(Timezone::get('BG'), 'Europe/Sofia');
        $this->assertSame(Timezone::get('SE'), 'Europe/Stockholm');
        $this->assertSame(Timezone::get('EE'), 'Europe/Tallinn');
        $this->assertSame(Timezone::get('AL'), 'Europe/Tirane');
        $this->assertSame(Timezone::get('LI'), 'Europe/Vaduz');
        $this->assertSame(Timezone::get('VA'), 'Europe/Vatican');
        $this->assertSame(Timezone::get('AT'), 'Europe/Vienna');
        $this->assertSame(Timezone::get('LT'), 'Europe/Vilnius');
        $this->assertSame(Timezone::get('PL'), 'Europe/Warsaw');
        $this->assertSame(Timezone::get('HR'), 'Europe/Zagreb');
        $this->assertSame(Timezone::get('IR'), 'Asia/Tehran');
        $this->assertSame(Timezone::get('MG'), 'Indian/Antananarivo');
        $this->assertSame(Timezone::get('CX'), 'Indian/Christmas');
        $this->assertSame(Timezone::get('CC'), 'Indian/Cocos');
        $this->assertSame(Timezone::get('KM'), 'Indian/Comoro');
        $this->assertSame(Timezone::get('MV'), 'Indian/Maldives');
        $this->assertSame(Timezone::get('MU'), 'Indian/Mauritius');
        $this->assertSame(Timezone::get('YT'), 'Indian/Mayotte');
        $this->assertSame(Timezone::get('RE'), 'Indian/Reunion');
        $this->assertSame(Timezone::get('FJ'), 'Pacific/Fiji');
        $this->assertSame(Timezone::get('TV'), 'Pacific/Funafuti');
        $this->assertSame(Timezone::get('GU'), 'Pacific/Guam');
        $this->assertSame(Timezone::get('NR'), 'Pacific/Nauru');
        $this->assertSame(Timezone::get('NU'), 'Pacific/Niue');
        $this->assertSame(Timezone::get('NF'), 'Pacific/Norfolk');
        $this->assertSame(Timezone::get('PW'), 'Pacific/Palau');
        $this->assertSame(Timezone::get('PN'), 'Pacific/Pitcairn');
        $this->assertSame(Timezone::get('CK'), 'Pacific/Rarotonga');
        $this->assertSame(Timezone::get('WS'), 'Pacific/Samoa');
        $this->assertSame(Timezone::get('KI'), 'Pacific/Tarawa');
        $this->assertSame(Timezone::get('TO'), 'Pacific/Tongatapu');
        $this->assertSame(Timezone::get('WF'), 'Pacific/Wallis');
        $this->assertSame(Timezone::get('TZ'), 'Africa/Dar_es_Salaam');
        $this->assertSame(Timezone::get('VN'), 'Asia/Phnom_Penh');
        $this->assertSame(Timezone::get('KH'), 'Asia/Phnom_Penh');
        $this->assertSame(Timezone::get('CM'), 'Africa/Lagos');
        $this->assertSame(Timezone::get('DO'), 'America/Santo_Domingo');
        $this->assertSame(Timezone::get('ET'), 'Africa/Addis_Ababa');
        $this->assertSame(Timezone::get('FX'), 'Europe/Paris');
        $this->assertSame(Timezone::get('HT'), 'America/Port-au-Prince');
        $this->assertSame(Timezone::get('CH'), 'Europe/Zurich');
        $this->assertSame(Timezone::get('AN'), 'America/Curacao');
        $this->assertSame(Timezone::get('BJ'), 'Africa/Porto-Novo');
        $this->assertSame(Timezone::get('EH'), 'Africa/El_Aaiun');
        $this->assertSame(Timezone::get('FK'), 'Atlantic/Stanley');
        $this->assertSame(Timezone::get('GF'), 'America/Cayenne');
        $this->assertSame(Timezone::get('IO'), 'Indian/Chagos');
        $this->assertSame(Timezone::get('MD'), 'Europe/Chisinau');
        $this->assertSame(Timezone::get('MP'), 'Pacific/Saipan');
        $this->assertSame(Timezone::get('MW'), 'Africa/Blantyre');
        $this->assertSame(Timezone::get('NA'), 'Africa/Windhoek');
        $this->assertSame(Timezone::get('NC'), 'Pacific/Noumea');
        $this->assertSame(Timezone::get('PG'), 'Pacific/Port_Moresby');
        $this->assertSame(Timezone::get('PM'), 'America/Miquelon');
        $this->assertSame(Timezone::get('PS'), 'Asia/Gaza');
        $this->assertSame(Timezone::get('PY'), 'America/Asuncion');
        $this->assertSame(Timezone::get('SB'), 'Pacific/Guadalcanal');
        $this->assertSame(Timezone::get('SC'), 'Indian/Mahe');
        $this->assertSame(Timezone::get('SJ'), 'Arctic/Longyearbyen');
        $this->assertSame(Timezone::get('SY'), 'Asia/Damascus');
        $this->assertSame(Timezone::get('TC'), 'America/Grand_Turk');
        $this->assertSame(Timezone::get('TF'), 'Indian/Kerguelen');
        $this->assertSame(Timezone::get('TK'), 'Pacific/Fakaofo');
        $this->assertSame(Timezone::get('TT'), 'America/Port_of_Spain');
        $this->assertSame(Timezone::get('VG'), 'America/Tortola');
        $this->assertSame(Timezone::get('VI'), 'America/St_Thomas');
        $this->assertSame(Timezone::get('VU'), 'Pacific/Efate');
        $this->assertSame(Timezone::get('RS'), 'Europe/Belgrade');
        $this->assertSame(Timezone::get('ME'), 'Europe/Podgorica');
        $this->assertSame(Timezone::get('AX'), 'Europe/Mariehamn');
        $this->assertSame(Timezone::get('GG'), 'Europe/Guernsey');
        $this->assertSame(Timezone::get('IM'), 'Europe/Isle_of_Man');
        $this->assertSame(Timezone::get('JE'), 'Europe/Jersey');
        $this->assertSame(Timezone::get('BL'), 'America/St_Barthelemy');
        $this->assertSame(Timezone::get('MF'), 'America/Marigot');
        $this->assertSame(Timezone::get('AR', '01'), 'America/Argentina/Buenos_Aires');
        $this->assertSame(Timezone::get('AR', '02'), 'America/Argentina/Catamarca');
        $this->assertSame(Timezone::get('AR', '03'), 'America/Argentina/Tucuman');
        $this->assertSame(Timezone::get('AR', '04'), 'America/Argentina/Rio_Gallegos');
        $this->assertSame(Timezone::get('AR', '05'), 'America/Argentina/Cordoba');
        $this->assertSame(Timezone::get('AR', '06'), 'America/Argentina/Tucuman');
        $this->assertSame(Timezone::get('AR', '07'), 'America/Argentina/Buenos_Aires');
        $this->assertSame(Timezone::get('AR', '08'), 'America/Argentina/Buenos_Aires');
        $this->assertSame(Timezone::get('AR', '09'), 'America/Argentina/Tucuman');
        $this->assertSame(Timezone::get('AR', '10'), 'America/Argentina/Jujuy');
        $this->assertSame(Timezone::get('AR', '11'), 'America/Argentina/San_Luis');
        $this->assertSame(Timezone::get('AR', '12'), 'America/Argentina/La_Rioja');
        $this->assertSame(Timezone::get('AR', '13'), 'America/Argentina/Mendoza');
        $this->assertSame(Timezone::get('AR', '14'), 'America/Argentina/Buenos_Aires');
        $this->assertSame(Timezone::get('AR', '15'), 'America/Argentina/San_Luis');
        $this->assertSame(Timezone::get('AR', '16'), 'America/Argentina/Buenos_Aires');
        $this->assertSame(Timezone::get('AR', '17'), 'America/Argentina/Salta');
        $this->assertSame(Timezone::get('AR', '18'), 'America/Argentina/San_Juan');
        $this->assertSame(Timezone::get('AR', '19'), 'America/Argentina/San_Luis');
        $this->assertSame(Timezone::get('AR', '20'), 'America/Argentina/Rio_Gallegos');
        $this->assertSame(Timezone::get('AR', '21'), 'America/Argentina/Buenos_Aires');
        $this->assertSame(Timezone::get('AR', '22'), 'America/Argentina/Catamarca');
        $this->assertSame(Timezone::get('AR', '23'), 'America/Argentina/Ushuaia');
        $this->assertSame(Timezone::get('AR', '24'), 'America/Argentina/Tucuman');
        $this->assertSame(Timezone::get('BR', '01'), 'America/Rio_Branco');
        $this->assertSame(Timezone::get('BR', '02'), 'America/Maceio');
        $this->assertSame(Timezone::get('BR', '03'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '04'), 'America/Manaus');
        $this->assertSame(Timezone::get('BR', '05'), 'America/Bahia');
        $this->assertSame(Timezone::get('BR', '06'), 'America/Fortaleza');
        $this->assertSame(Timezone::get('BR', '07'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '08'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '11'), 'America/Campo_Grande');
        $this->assertSame(Timezone::get('BR', '13'), 'America/Belem');
        $this->assertSame(Timezone::get('BR', '14'), 'America/Cuiaba');
        $this->assertSame(Timezone::get('BR', '15'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '16'), 'America/Belem');
        $this->assertSame(Timezone::get('BR', '17'), 'America/Recife');
        $this->assertSame(Timezone::get('BR', '18'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '20'), 'America/Fortaleza');
        $this->assertSame(Timezone::get('BR', '21'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '22'), 'America/Recife');
        $this->assertSame(Timezone::get('BR', '23'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '24'), 'America/Porto_Velho');
        $this->assertSame(Timezone::get('BR', '25'), 'America/Boa_Vista');
        $this->assertSame(Timezone::get('BR', '26'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '27'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '28'), 'America/Maceio');
        $this->assertSame(Timezone::get('BR', '29'), 'America/Sao_Paulo');
        $this->assertSame(Timezone::get('BR', '30'), 'America/Recife');
        $this->assertSame(Timezone::get('BR', '31'), 'America/Araguaina');
        $this->assertSame(Timezone::get('CD', '02'), 'Africa/Kinshasa');
        $this->assertSame(Timezone::get('CD', '05'), 'Africa/Lubumbashi');
        $this->assertSame(Timezone::get('CD', '06'), 'Africa/Kinshasa');
        $this->assertSame(Timezone::get('CD', '08'), 'Africa/Kinshasa');
        $this->assertSame(Timezone::get('CD', '10'), 'Africa/Lubumbashi');
        $this->assertSame(Timezone::get('CD', '11'), 'Africa/Lubumbashi');
        $this->assertSame(Timezone::get('CD', '12'), 'Africa/Lubumbashi');
        $this->assertSame(Timezone::get('CN', '01'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '02'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '03'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '04'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '05'), 'Asia/Harbin');
        $this->assertSame(Timezone::get('CN', '06'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '07'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '08'), 'Asia/Harbin');
        $this->assertSame(Timezone::get('CN', '09'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '10'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '11'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '12'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '13'), 'Asia/Urumqi');
        $this->assertSame(Timezone::get('CN', '14'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '15'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '16'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '18'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '19'), 'Asia/Harbin');
        $this->assertSame(Timezone::get('CN', '20'), 'Asia/Harbin');
        $this->assertSame(Timezone::get('CN', '21'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '22'), 'Asia/Harbin');
        $this->assertSame(Timezone::get('CN', '23'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '24'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '25'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '26'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '28'), 'Asia/Shanghai');
        $this->assertSame(Timezone::get('CN', '29'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '30'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '31'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '32'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('CN', '33'), 'Asia/Chongqing');
        $this->assertSame(Timezone::get('EC', '01'), 'Pacific/Galapagos');
        $this->assertSame(Timezone::get('EC', '02'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '03'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '04'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '05'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '06'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '07'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '08'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '09'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '10'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '11'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '12'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '13'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '14'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '15'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '17'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '18'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '19'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '20'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('EC', '22'), 'America/Guayaquil');
        $this->assertSame(Timezone::get('ES', '07'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '27'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '29'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '31'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '32'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '34'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '39'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '51'), 'Africa/Ceuta');
        $this->assertSame(Timezone::get('ES', '52'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '53'), 'Atlantic/Canary');
        $this->assertSame(Timezone::get('ES', '54'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '55'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '56'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '57'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '58'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '59'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('ES', '60'), 'Europe/Madrid');
        $this->assertSame(Timezone::get('GL', '01'), 'America/Thule');
        $this->assertSame(Timezone::get('GL', '02'), 'America/Godthab');
        $this->assertSame(Timezone::get('GL', '03'), 'America/Godthab');
        $this->assertSame(Timezone::get('ID', '01'), 'Asia/Pontianak');
        $this->assertSame(Timezone::get('ID', '02'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '03'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '04'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '05'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '06'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '07'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '08'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '09'), 'Asia/Jayapura');
        $this->assertSame(Timezone::get('ID', '10'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '11'), 'Asia/Pontianak');
        $this->assertSame(Timezone::get('ID', '12'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '13'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '14'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '15'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '16'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '17'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '18'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '19'), 'Asia/Pontianak');
        $this->assertSame(Timezone::get('ID', '20'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '21'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '22'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '23'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '24'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '25'), 'Asia/Pontianak');
        $this->assertSame(Timezone::get('ID', '26'), 'Asia/Pontianak');
        $this->assertSame(Timezone::get('ID', '30'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('ID', '31'), 'Asia/Makassar');
        $this->assertSame(Timezone::get('ID', '33'), 'Asia/Jakarta');
        $this->assertSame(Timezone::get('KZ', '01'), 'Asia/Almaty');
        $this->assertSame(Timezone::get('KZ', '02'), 'Asia/Almaty');
        $this->assertSame(Timezone::get('KZ', '03'), 'Asia/Qyzylorda');
        $this->assertSame(Timezone::get('KZ', '04'), 'Asia/Aqtobe');
        $this->assertSame(Timezone::get('KZ', '05'), 'Asia/Qyzylorda');
        $this->assertSame(Timezone::get('KZ', '06'), 'Asia/Aqtau');
        $this->assertSame(Timezone::get('KZ', '07'), 'Asia/Oral');
        $this->assertSame(Timezone::get('KZ', '08'), 'Asia/Qyzylorda');
        $this->assertSame(Timezone::get('KZ', '09'), 'Asia/Aqtau');
        $this->assertSame(Timezone::get('KZ', '10'), 'Asia/Qyzylorda');
        $this->assertSame(Timezone::get('KZ', '11'), 'Asia/Almaty');
        $this->assertSame(Timezone::get('KZ', '12'), 'Asia/Qyzylorda');
        $this->assertSame(Timezone::get('KZ', '13'), 'Asia/Aqtobe');
        $this->assertSame(Timezone::get('KZ', '14'), 'Asia/Qyzylorda');
        $this->assertSame(Timezone::get('KZ', '15'), 'Asia/Almaty');
        $this->assertSame(Timezone::get('KZ', '16'), 'Asia/Aqtobe');
        $this->assertSame(Timezone::get('KZ', '17'), 'Asia/Almaty');
        $this->assertSame(Timezone::get('MX', '01'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '02'), 'America/Tijuana');
        $this->assertSame(Timezone::get('MX', '03'), 'America/Hermosillo');
        $this->assertSame(Timezone::get('MX', '04'), 'America/Merida');
        $this->assertSame(Timezone::get('MX', '05'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '06'), 'America/Chihuahua');
        $this->assertSame(Timezone::get('MX', '07'), 'America/Monterrey');
        $this->assertSame(Timezone::get('MX', '08'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '09'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '10'), 'America/Mazatlan');
        $this->assertSame(Timezone::get('MX', '11'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '12'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '13'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '14'), 'America/Mazatlan');
        $this->assertSame(Timezone::get('MX', '15'), 'America/Chihuahua');
        $this->assertSame(Timezone::get('MX', '16'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '17'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '18'), 'America/Mazatlan');
        $this->assertSame(Timezone::get('MX', '19'), 'America/Monterrey');
        $this->assertSame(Timezone::get('MX', '20'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '21'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '22'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '23'), 'America/Cancun');
        $this->assertSame(Timezone::get('MX', '24'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '25'), 'America/Mazatlan');
        $this->assertSame(Timezone::get('MX', '26'), 'America/Hermosillo');
        $this->assertSame(Timezone::get('MX', '27'), 'America/Merida');
        $this->assertSame(Timezone::get('MX', '28'), 'America/Monterrey');
        $this->assertSame(Timezone::get('MX', '29'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '30'), 'America/Mexico_City');
        $this->assertSame(Timezone::get('MX', '31'), 'America/Merida');
        $this->assertSame(Timezone::get('MX', '32'), 'America/Monterrey');
        $this->assertSame(Timezone::get('MY', '01'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '02'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '03'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '04'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '05'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '06'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '07'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '08'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '09'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '11'), 'Asia/Kuching');
        $this->assertSame(Timezone::get('MY', '12'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '13'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '14'), 'Asia/Kuala_Lumpur');
        $this->assertSame(Timezone::get('MY', '15'), 'Asia/Kuching');
        $this->assertSame(Timezone::get('MY', '16'), 'Asia/Kuching');
        $this->assertSame(Timezone::get('NZ', '85'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'E7'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'E8'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'E9'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F1'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F2'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F3'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F4'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F5'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F7'), 'Pacific/Chatham');
        $this->assertSame(Timezone::get('NZ', 'F8'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'F9'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'G1'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'G2'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('NZ', 'G3'), 'Pacific/Auckland');
        $this->assertSame(Timezone::get('PT', '02'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '03'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '04'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '05'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '06'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '07'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '08'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '09'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '10'), 'Atlantic/Madeira');
        $this->assertSame(Timezone::get('PT', '11'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '13'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '14'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '16'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '17'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '18'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '19'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '20'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '21'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('PT', '22'), 'Europe/Lisbon');
        $this->assertSame(Timezone::get('RU', '01'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '02'), 'Asia/Irkutsk');
        $this->assertSame(Timezone::get('RU', '03'), 'Asia/Novokuznetsk');
        $this->assertSame(Timezone::get('RU', '04'), 'Asia/Novosibirsk');
        $this->assertSame(Timezone::get('RU', '05'), 'Asia/Vladivostok');
        $this->assertSame(Timezone::get('RU', '06'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '07'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '08'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '09'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '10'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '11'), 'Asia/Irkutsk');
        $this->assertSame(Timezone::get('RU', '13'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '14'), 'Asia/Irkutsk');
        $this->assertSame(Timezone::get('RU', '15'), 'Asia/Anadyr');
        $this->assertSame(Timezone::get('RU', '16'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '17'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '18'), 'Asia/Krasnoyarsk');
        $this->assertSame(Timezone::get('RU', '20'), 'Asia/Irkutsk');
        $this->assertSame(Timezone::get('RU', '21'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '22'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '23'), 'Europe/Kaliningrad');
        $this->assertSame(Timezone::get('RU', '24'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '25'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '26'), 'Asia/Kamchatka');
        $this->assertSame(Timezone::get('RU', '27'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '28'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '29'), 'Asia/Novokuznetsk');
        $this->assertSame(Timezone::get('RU', '30'), 'Asia/Vladivostok');
        $this->assertSame(Timezone::get('RU', '31'), 'Asia/Krasnoyarsk');
        $this->assertSame(Timezone::get('RU', '32'), 'Asia/Omsk');
        $this->assertSame(Timezone::get('RU', '33'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '34'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '35'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '36'), 'Asia/Anadyr');
        $this->assertSame(Timezone::get('RU', '37'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '38'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '39'), 'Asia/Krasnoyarsk');
        $this->assertSame(Timezone::get('RU', '40'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '41'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '42'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '43'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '44'), 'Asia/Magadan');
        $this->assertSame(Timezone::get('RU', '45'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '46'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '47'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '48'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '49'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '50'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '51'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '52'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '53'), 'Asia/Novosibirsk');
        $this->assertSame(Timezone::get('RU', '54'), 'Asia/Omsk');
        $this->assertSame(Timezone::get('RU', '55'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '56'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '57'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '58'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '59'), 'Asia/Vladivostok');
        $this->assertSame(Timezone::get('RU', '60'), 'Europe/Kaliningrad');
        $this->assertSame(Timezone::get('RU', '61'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '62'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '63'), 'Asia/Yakutsk');
        $this->assertSame(Timezone::get('RU', '64'), 'Asia/Sakhalin');
        $this->assertSame(Timezone::get('RU', '65'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '66'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '67'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '68'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '69'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '70'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '71'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '72'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '73'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '74'), 'Asia/Krasnoyarsk');
        $this->assertSame(Timezone::get('RU', '75'), 'Asia/Novosibirsk');
        $this->assertSame(Timezone::get('RU', '76'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '77'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '78'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '79'), 'Asia/Irkutsk');
        $this->assertSame(Timezone::get('RU', '80'), 'Asia/Yekaterinburg');
        $this->assertSame(Timezone::get('RU', '81'), 'Europe/Samara');
        $this->assertSame(Timezone::get('RU', '82'), 'Asia/Irkutsk');
        $this->assertSame(Timezone::get('RU', '83'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '84'), 'Europe/Volgograd');
        $this->assertSame(Timezone::get('RU', '85'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '86'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '87'), 'Asia/Novosibirsk');
        $this->assertSame(Timezone::get('RU', '88'), 'Europe/Moscow');
        $this->assertSame(Timezone::get('RU', '89'), 'Asia/Vladivostok');
        $this->assertSame(Timezone::get('UA', '01'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '02'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '03'), 'Europe/Uzhgorod');
        $this->assertSame(Timezone::get('UA', '04'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '05'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '06'), 'Europe/Uzhgorod');
        $this->assertSame(Timezone::get('UA', '07'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '08'), 'Europe/Simferopol');
        $this->assertSame(Timezone::get('UA', '09'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '10'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '11'), 'Europe/Simferopol');
        $this->assertSame(Timezone::get('UA', '13'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '14'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '15'), 'Europe/Uzhgorod');
        $this->assertSame(Timezone::get('UA', '16'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '17'), 'Europe/Simferopol');
        $this->assertSame(Timezone::get('UA', '18'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '19'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '20'), 'Europe/Simferopol');
        $this->assertSame(Timezone::get('UA', '21'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '22'), 'Europe/Uzhgorod');
        $this->assertSame(Timezone::get('UA', '23'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UA', '24'), 'Europe/Uzhgorod');
        $this->assertSame(Timezone::get('UA', '25'), 'Europe/Uzhgorod');
        $this->assertSame(Timezone::get('UA', '26'), 'Europe/Zaporozhye');
        $this->assertSame(Timezone::get('UA', '27'), 'Europe/Kiev');
        $this->assertSame(Timezone::get('UZ', '01'), 'Asia/Tashkent');
        $this->assertSame(Timezone::get('UZ', '02'), 'Asia/Samarkand');
        $this->assertSame(Timezone::get('UZ', '03'), 'Asia/Tashkent');
        $this->assertSame(Timezone::get('UZ', '06'), 'Asia/Tashkent');
        $this->assertSame(Timezone::get('UZ', '07'), 'Asia/Samarkand');
        $this->assertSame(Timezone::get('UZ', '08'), 'Asia/Samarkand');
        $this->assertSame(Timezone::get('UZ', '09'), 'Asia/Samarkand');
        $this->assertSame(Timezone::get('UZ', '10'), 'Asia/Samarkand');
        $this->assertSame(Timezone::get('UZ', '12'), 'Asia/Samarkand');
        $this->assertSame(Timezone::get('UZ', '13'), 'Asia/Tashkent');
        $this->assertSame(Timezone::get('UZ', '14'), 'Asia/Tashkent');
        $this->assertSame(Timezone::get('TL'), 'Asia/Dili');
        $this->assertSame(Timezone::get('PF'), 'Pacific/Marquesas');
    }

}
