<?php
/**
 * Project: PHP Light Framework
 *
 * @author      Michal Szewczyk <ms@msworks.pl>
 * @copyright   Michal Szewczyk
 * @license     MIT
 */
declare(strict_types=1);

use MS\LightFramework\Html\Tags;
use MS\LightFramework\Html\Controlls\DateAndTime;
use PHPUnit\Framework\TestCase;


class DateAndTimeTest extends TestCase
{

    public function testInputTimestamp()
    {
        $expected = '<div class="timestamp-controll cf"><input type="text" name="MFVARS[test_date]" value="" id="test_date" class="date"/><input type="text" name="MFVARS[test_time]" value="" id="test_time" class="time"/><span class="timestamp-reset" title="TXT_PANEL_DATA_FORM_TIMESTAMP_CONTROLL_RESET"/></div>';
        $this->assertEquals($expected, DateAndTime::inputTimestamp('test', 0, ['class' => 'testclass']));
    }

    public function testSelectTimestampDefault()
    {
        $expected = '<div class="timestamp-controll cf"><div class="select-wrapper year"><select name="MFVARS[test_y]" id="test_y" data-selected="-1" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1" selected="selected">TXT_DATETIME_YYYY</option>'.Tags::CRLF;
        $expected .= '<option value="1978" class="opt-1978">1978</option>'.Tags::CRLF;
        $expected .= '<option value="1979" class="opt-1979">1979</option>'.Tags::CRLF;
        $expected .= '<option value="1980" class="opt-1980">1980</option>'.Tags::CRLF;
        $expected .= '<option value="1981" class="opt-1981">1981</option>'.Tags::CRLF;
        $expected .= '<option value="1982" class="opt-1982">1982</option>'.Tags::CRLF;
        $expected .= '<option value="1983" class="opt-1983">1983</option>'.Tags::CRLF;
        $expected .= '<option value="1984" class="opt-1984">1984</option>'.Tags::CRLF;
        $expected .= '<option value="1985" class="opt-1985">1985</option>'.Tags::CRLF;
        $expected .= '<option value="1986" class="opt-1986">1986</option>'.Tags::CRLF;
        $expected .= '<option value="1987" class="opt-1987">1987</option>'.Tags::CRLF;
        $expected .= '<option value="1988" class="opt-1988">1988</option>'.Tags::CRLF;
        $expected .= '<option value="1989" class="opt-1989">1989</option>'.Tags::CRLF;
        $expected .= '<option value="1990" class="opt-1990">1990</option>'.Tags::CRLF;
        $expected .= '<option value="1991" class="opt-1991">1991</option>'.Tags::CRLF;
        $expected .= '<option value="1992" class="opt-1992">1992</option>'.Tags::CRLF;
        $expected .= '<option value="1993" class="opt-1993">1993</option>'.Tags::CRLF;
        $expected .= '<option value="1994" class="opt-1994">1994</option>'.Tags::CRLF;
        $expected .= '<option value="1995" class="opt-1995">1995</option>'.Tags::CRLF;
        $expected .= '<option value="1996" class="opt-1996">1996</option>'.Tags::CRLF;
        $expected .= '<option value="1997" class="opt-1997">1997</option>'.Tags::CRLF;
        $expected .= '<option value="1998" class="opt-1998">1998</option>'.Tags::CRLF;
        $expected .= '<option value="1999" class="opt-1999">1999</option>'.Tags::CRLF;
        $expected .= '<option value="2000" class="opt-2000">2000</option>'.Tags::CRLF;
        $expected .= '<option value="2001" class="opt-2001">2001</option>'.Tags::CRLF;
        $expected .= '<option value="2002" class="opt-2002">2002</option>'.Tags::CRLF;
        $expected .= '<option value="2003" class="opt-2003">2003</option>'.Tags::CRLF;
        $expected .= '<option value="2004" class="opt-2004">2004</option>'.Tags::CRLF;
        $expected .= '<option value="2005" class="opt-2005">2005</option>'.Tags::CRLF;
        $expected .= '<option value="2006" class="opt-2006">2006</option>'.Tags::CRLF;
        $expected .= '<option value="2007" class="opt-2007">2007</option>'.Tags::CRLF;
        $expected .= '<option value="2008" class="opt-2008">2008</option>'.Tags::CRLF;
        $expected .= '<option value="2009" class="opt-2009">2009</option>'.Tags::CRLF;
        $expected .= '<option value="2010" class="opt-2010">2010</option>'.Tags::CRLF;
        $expected .= '<option value="2011" class="opt-2011">2011</option>'.Tags::CRLF;
        $expected .= '<option value="2012" class="opt-2012">2012</option>'.Tags::CRLF;
        $expected .= '<option value="2013" class="opt-2013">2013</option>'.Tags::CRLF;
        $expected .= '<option value="2014" class="opt-2014">2014</option>'.Tags::CRLF;
        $expected .= '<option value="2015" class="opt-2015">2015</option>'.Tags::CRLF;
        $expected .= '<option value="2016" class="opt-2016">2016</option>'.Tags::CRLF;
        $expected .= '<option value="2017" class="opt-2017">2017</option>'.Tags::CRLF;
        $expected .= '<option value="2018" class="opt-2018">2018</option>'.Tags::CRLF;
        $expected .= '<option value="2019" class="opt-2019">2019</option>'.Tags::CRLF;
        $expected .= '<option value="2020" class="opt-2020">2020</option>'.Tags::CRLF;
        $expected .= '<option value="2021" class="opt-2021">2021</option>'.Tags::CRLF;
        $expected .= '<option value="2022" class="opt-2022">2022</option>'.Tags::CRLF;
        $expected .= '<option value="2023" class="opt-2023">2023</option>'.Tags::CRLF;
        $expected .= '<option value="2024" class="opt-2024">2024</option>'.Tags::CRLF;
        $expected .= '<option value="2025" class="opt-2025">2025</option>'.Tags::CRLF;
        $expected .= '<option value="2026" class="opt-2026">2026</option>'.Tags::CRLF;
        $expected .= '<option value="2027" class="opt-2027">2027</option>'.Tags::CRLF;
        $expected .= '<option value="2028" class="opt-2028">2028</option>'.Tags::CRLF;
        $expected .= '<option value="2029" class="opt-2029">2029</option>'.Tags::CRLF;
        $expected .= '<option value="2030" class="opt-2030">2030</option>'.Tags::CRLF;
        $expected .= '<option value="2031" class="opt-2031">2031</option>'.Tags::CRLF;
        $expected .= '<option value="2032" class="opt-2032">2032</option>'.Tags::CRLF;
        $expected .= '<option value="2033" class="opt-2033">2033</option>'.Tags::CRLF;
        $expected .= '<option value="2034" class="opt-2034">2034</option>'.Tags::CRLF;
        $expected .= '<option value="2035" class="opt-2035">2035</option>'.Tags::CRLF;
        $expected .= '<option value="2036" class="opt-2036">2036</option>'.Tags::CRLF;
        $expected .= '<option value="2037" class="opt-2037">2037</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper month"><select name="MFVARS[test_m]" id="test_m" data-selected="-1" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1" selected="selected">TXT_DATETIME_MMM</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">TXT_DATETIME_MONTH_1_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">TXT_DATETIME_MONTH_2_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">TXT_DATETIME_MONTH_3_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">TXT_DATETIME_MONTH_4_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">TXT_DATETIME_MONTH_5_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">TXT_DATETIME_MONTH_6_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">TXT_DATETIME_MONTH_7_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">TXT_DATETIME_MONTH_8_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">TXT_DATETIME_MONTH_9_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">TXT_DATETIME_MONTH_10_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">TXT_DATETIME_MONTH_11_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">TXT_DATETIME_MONTH_12_SHORT</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper day"><select name="MFVARS[test_d]" id="test_d" data-selected="-1" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1" selected="selected">TXT_DATETIME_DD</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '<option value="24" class="opt-24">24</option>'.Tags::CRLF;
        $expected .= '<option value="25" class="opt-25">25</option>'.Tags::CRLF;
        $expected .= '<option value="26" class="opt-26">26</option>'.Tags::CRLF;
        $expected .= '<option value="27" class="opt-27">27</option>'.Tags::CRLF;
        $expected .= '<option value="28" class="opt-28">28</option>'.Tags::CRLF;
        $expected .= '<option value="29" class="opt-29">29</option>'.Tags::CRLF;
        $expected .= '<option value="30" class="opt-30">30</option>'.Tags::CRLF;
        $expected .= '<option value="31" class="opt-31">31</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper hour"><select name="MFVARS[test_h]" id="test_h" data-selected="-1" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1" selected="selected">TXT_DATETIME_HH</option>'.Tags::CRLF;
        $expected .= '<option value="0" class="opt-0">00</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper minute"><select name="MFVARS[test_i]" id="test_i" data-selected="-1" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1" selected="selected">TXT_DATETIME_II</option>'.Tags::CRLF;
        $expected .= '<option value="0" class="opt-0">00</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '<option value="24" class="opt-24">24</option>'.Tags::CRLF;
        $expected .= '<option value="25" class="opt-25">25</option>'.Tags::CRLF;
        $expected .= '<option value="26" class="opt-26">26</option>'.Tags::CRLF;
        $expected .= '<option value="27" class="opt-27">27</option>'.Tags::CRLF;
        $expected .= '<option value="28" class="opt-28">28</option>'.Tags::CRLF;
        $expected .= '<option value="29" class="opt-29">29</option>'.Tags::CRLF;
        $expected .= '<option value="30" class="opt-30">30</option>'.Tags::CRLF;
        $expected .= '<option value="31" class="opt-31">31</option>'.Tags::CRLF;
        $expected .= '<option value="32" class="opt-32">32</option>'.Tags::CRLF;
        $expected .= '<option value="33" class="opt-33">33</option>'.Tags::CRLF;
        $expected .= '<option value="34" class="opt-34">34</option>'.Tags::CRLF;
        $expected .= '<option value="35" class="opt-35">35</option>'.Tags::CRLF;
        $expected .= '<option value="36" class="opt-36">36</option>'.Tags::CRLF;
        $expected .= '<option value="37" class="opt-37">37</option>'.Tags::CRLF;
        $expected .= '<option value="38" class="opt-38">38</option>'.Tags::CRLF;
        $expected .= '<option value="39" class="opt-39">39</option>'.Tags::CRLF;
        $expected .= '<option value="40" class="opt-40">40</option>'.Tags::CRLF;
        $expected .= '<option value="41" class="opt-41">41</option>'.Tags::CRLF;
        $expected .= '<option value="42" class="opt-42">42</option>'.Tags::CRLF;
        $expected .= '<option value="43" class="opt-43">43</option>'.Tags::CRLF;
        $expected .= '<option value="44" class="opt-44">44</option>'.Tags::CRLF;
        $expected .= '<option value="45" class="opt-45">45</option>'.Tags::CRLF;
        $expected .= '<option value="46" class="opt-46">46</option>'.Tags::CRLF;
        $expected .= '<option value="47" class="opt-47">47</option>'.Tags::CRLF;
        $expected .= '<option value="48" class="opt-48">48</option>'.Tags::CRLF;
        $expected .= '<option value="49" class="opt-49">49</option>'.Tags::CRLF;
        $expected .= '<option value="50" class="opt-50">50</option>'.Tags::CRLF;
        $expected .= '<option value="51" class="opt-51">51</option>'.Tags::CRLF;
        $expected .= '<option value="52" class="opt-52">52</option>'.Tags::CRLF;
        $expected .= '<option value="53" class="opt-53">53</option>'.Tags::CRLF;
        $expected .= '<option value="54" class="opt-54">54</option>'.Tags::CRLF;
        $expected .= '<option value="55" class="opt-55">55</option>'.Tags::CRLF;
        $expected .= '<option value="56" class="opt-56">56</option>'.Tags::CRLF;
        $expected .= '<option value="57" class="opt-57">57</option>'.Tags::CRLF;
        $expected .= '<option value="58" class="opt-58">58</option>'.Tags::CRLF;
        $expected .= '<option value="59" class="opt-59">59</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper second"><select name="MFVARS[test_s]" id="test_s" data-selected="-1" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1" selected="selected">TXT_DATETIME_SS</option>'.Tags::CRLF;
        $expected .= '<option value="0" class="opt-0">00</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '<option value="24" class="opt-24">24</option>'.Tags::CRLF;
        $expected .= '<option value="25" class="opt-25">25</option>'.Tags::CRLF;
        $expected .= '<option value="26" class="opt-26">26</option>'.Tags::CRLF;
        $expected .= '<option value="27" class="opt-27">27</option>'.Tags::CRLF;
        $expected .= '<option value="28" class="opt-28">28</option>'.Tags::CRLF;
        $expected .= '<option value="29" class="opt-29">29</option>'.Tags::CRLF;
        $expected .= '<option value="30" class="opt-30">30</option>'.Tags::CRLF;
        $expected .= '<option value="31" class="opt-31">31</option>'.Tags::CRLF;
        $expected .= '<option value="32" class="opt-32">32</option>'.Tags::CRLF;
        $expected .= '<option value="33" class="opt-33">33</option>'.Tags::CRLF;
        $expected .= '<option value="34" class="opt-34">34</option>'.Tags::CRLF;
        $expected .= '<option value="35" class="opt-35">35</option>'.Tags::CRLF;
        $expected .= '<option value="36" class="opt-36">36</option>'.Tags::CRLF;
        $expected .= '<option value="37" class="opt-37">37</option>'.Tags::CRLF;
        $expected .= '<option value="38" class="opt-38">38</option>'.Tags::CRLF;
        $expected .= '<option value="39" class="opt-39">39</option>'.Tags::CRLF;
        $expected .= '<option value="40" class="opt-40">40</option>'.Tags::CRLF;
        $expected .= '<option value="41" class="opt-41">41</option>'.Tags::CRLF;
        $expected .= '<option value="42" class="opt-42">42</option>'.Tags::CRLF;
        $expected .= '<option value="43" class="opt-43">43</option>'.Tags::CRLF;
        $expected .= '<option value="44" class="opt-44">44</option>'.Tags::CRLF;
        $expected .= '<option value="45" class="opt-45">45</option>'.Tags::CRLF;
        $expected .= '<option value="46" class="opt-46">46</option>'.Tags::CRLF;
        $expected .= '<option value="47" class="opt-47">47</option>'.Tags::CRLF;
        $expected .= '<option value="48" class="opt-48">48</option>'.Tags::CRLF;
        $expected .= '<option value="49" class="opt-49">49</option>'.Tags::CRLF;
        $expected .= '<option value="50" class="opt-50">50</option>'.Tags::CRLF;
        $expected .= '<option value="51" class="opt-51">51</option>'.Tags::CRLF;
        $expected .= '<option value="52" class="opt-52">52</option>'.Tags::CRLF;
        $expected .= '<option value="53" class="opt-53">53</option>'.Tags::CRLF;
        $expected .= '<option value="54" class="opt-54">54</option>'.Tags::CRLF;
        $expected .= '<option value="55" class="opt-55">55</option>'.Tags::CRLF;
        $expected .= '<option value="56" class="opt-56">56</option>'.Tags::CRLF;
        $expected .= '<option value="57" class="opt-57">57</option>'.Tags::CRLF;
        $expected .= '<option value="58" class="opt-58">58</option>'.Tags::CRLF;
        $expected .= '<option value="59" class="opt-59">59</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<span class="timestamp-reset" title="TXT_PANEL_DATA_FORM_TIMESTAMP_CONTROLL_RESET"/></div>';
        $this->assertEquals($expected, DateAndTime::selectTimestamp('test', 0, ['class' => 'testclass']));
    }

    public function testSelectTimestampExpected()
    {
        $expected = '<div class="timestamp-controll cf"><div class="select-wrapper year"><select name="MFVARS[test_y]" id="test_y" data-selected="1978" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1">TXT_DATETIME_YYYY</option>'.Tags::CRLF;
        $expected .= '<option value="1978" class="opt-1978" selected="selected">1978</option>'.Tags::CRLF;
        $expected .= '<option value="1979" class="opt-1979">1979</option>'.Tags::CRLF;
        $expected .= '<option value="1980" class="opt-1980">1980</option>'.Tags::CRLF;
        $expected .= '<option value="1981" class="opt-1981">1981</option>'.Tags::CRLF;
        $expected .= '<option value="1982" class="opt-1982">1982</option>'.Tags::CRLF;
        $expected .= '<option value="1983" class="opt-1983">1983</option>'.Tags::CRLF;
        $expected .= '<option value="1984" class="opt-1984">1984</option>'.Tags::CRLF;
        $expected .= '<option value="1985" class="opt-1985">1985</option>'.Tags::CRLF;
        $expected .= '<option value="1986" class="opt-1986">1986</option>'.Tags::CRLF;
        $expected .= '<option value="1987" class="opt-1987">1987</option>'.Tags::CRLF;
        $expected .= '<option value="1988" class="opt-1988">1988</option>'.Tags::CRLF;
        $expected .= '<option value="1989" class="opt-1989">1989</option>'.Tags::CRLF;
        $expected .= '<option value="1990" class="opt-1990">1990</option>'.Tags::CRLF;
        $expected .= '<option value="1991" class="opt-1991">1991</option>'.Tags::CRLF;
        $expected .= '<option value="1992" class="opt-1992">1992</option>'.Tags::CRLF;
        $expected .= '<option value="1993" class="opt-1993">1993</option>'.Tags::CRLF;
        $expected .= '<option value="1994" class="opt-1994">1994</option>'.Tags::CRLF;
        $expected .= '<option value="1995" class="opt-1995">1995</option>'.Tags::CRLF;
        $expected .= '<option value="1996" class="opt-1996">1996</option>'.Tags::CRLF;
        $expected .= '<option value="1997" class="opt-1997">1997</option>'.Tags::CRLF;
        $expected .= '<option value="1998" class="opt-1998">1998</option>'.Tags::CRLF;
        $expected .= '<option value="1999" class="opt-1999">1999</option>'.Tags::CRLF;
        $expected .= '<option value="2000" class="opt-2000">2000</option>'.Tags::CRLF;
        $expected .= '<option value="2001" class="opt-2001">2001</option>'.Tags::CRLF;
        $expected .= '<option value="2002" class="opt-2002">2002</option>'.Tags::CRLF;
        $expected .= '<option value="2003" class="opt-2003">2003</option>'.Tags::CRLF;
        $expected .= '<option value="2004" class="opt-2004">2004</option>'.Tags::CRLF;
        $expected .= '<option value="2005" class="opt-2005">2005</option>'.Tags::CRLF;
        $expected .= '<option value="2006" class="opt-2006">2006</option>'.Tags::CRLF;
        $expected .= '<option value="2007" class="opt-2007">2007</option>'.Tags::CRLF;
        $expected .= '<option value="2008" class="opt-2008">2008</option>'.Tags::CRLF;
        $expected .= '<option value="2009" class="opt-2009">2009</option>'.Tags::CRLF;
        $expected .= '<option value="2010" class="opt-2010">2010</option>'.Tags::CRLF;
        $expected .= '<option value="2011" class="opt-2011">2011</option>'.Tags::CRLF;
        $expected .= '<option value="2012" class="opt-2012">2012</option>'.Tags::CRLF;
        $expected .= '<option value="2013" class="opt-2013">2013</option>'.Tags::CRLF;
        $expected .= '<option value="2014" class="opt-2014">2014</option>'.Tags::CRLF;
        $expected .= '<option value="2015" class="opt-2015">2015</option>'.Tags::CRLF;
        $expected .= '<option value="2016" class="opt-2016">2016</option>'.Tags::CRLF;
        $expected .= '<option value="2017" class="opt-2017">2017</option>'.Tags::CRLF;
        $expected .= '<option value="2018" class="opt-2018">2018</option>'.Tags::CRLF;
        $expected .= '<option value="2019" class="opt-2019">2019</option>'.Tags::CRLF;
        $expected .= '<option value="2020" class="opt-2020">2020</option>'.Tags::CRLF;
        $expected .= '<option value="2021" class="opt-2021">2021</option>'.Tags::CRLF;
        $expected .= '<option value="2022" class="opt-2022">2022</option>'.Tags::CRLF;
        $expected .= '<option value="2023" class="opt-2023">2023</option>'.Tags::CRLF;
        $expected .= '<option value="2024" class="opt-2024">2024</option>'.Tags::CRLF;
        $expected .= '<option value="2025" class="opt-2025">2025</option>'.Tags::CRLF;
        $expected .= '<option value="2026" class="opt-2026">2026</option>'.Tags::CRLF;
        $expected .= '<option value="2027" class="opt-2027">2027</option>'.Tags::CRLF;
        $expected .= '<option value="2028" class="opt-2028">2028</option>'.Tags::CRLF;
        $expected .= '<option value="2029" class="opt-2029">2029</option>'.Tags::CRLF;
        $expected .= '<option value="2030" class="opt-2030">2030</option>'.Tags::CRLF;
        $expected .= '<option value="2031" class="opt-2031">2031</option>'.Tags::CRLF;
        $expected .= '<option value="2032" class="opt-2032">2032</option>'.Tags::CRLF;
        $expected .= '<option value="2033" class="opt-2033">2033</option>'.Tags::CRLF;
        $expected .= '<option value="2034" class="opt-2034">2034</option>'.Tags::CRLF;
        $expected .= '<option value="2035" class="opt-2035">2035</option>'.Tags::CRLF;
        $expected .= '<option value="2036" class="opt-2036">2036</option>'.Tags::CRLF;
        $expected .= '<option value="2037" class="opt-2037">2037</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper month"><select name="MFVARS[test_m]" id="test_m" data-selected="4" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1">TXT_DATETIME_MMM</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">TXT_DATETIME_MONTH_1_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">TXT_DATETIME_MONTH_2_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">TXT_DATETIME_MONTH_3_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4" selected="selected">TXT_DATETIME_MONTH_4_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">TXT_DATETIME_MONTH_5_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">TXT_DATETIME_MONTH_6_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">TXT_DATETIME_MONTH_7_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">TXT_DATETIME_MONTH_8_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">TXT_DATETIME_MONTH_9_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">TXT_DATETIME_MONTH_10_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">TXT_DATETIME_MONTH_11_SHORT</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">TXT_DATETIME_MONTH_12_SHORT</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper day"><select name="MFVARS[test_d]" id="test_d" data-selected="15" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1">TXT_DATETIME_DD</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15" selected="selected">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '<option value="24" class="opt-24">24</option>'.Tags::CRLF;
        $expected .= '<option value="25" class="opt-25">25</option>'.Tags::CRLF;
        $expected .= '<option value="26" class="opt-26">26</option>'.Tags::CRLF;
        $expected .= '<option value="27" class="opt-27">27</option>'.Tags::CRLF;
        $expected .= '<option value="28" class="opt-28">28</option>'.Tags::CRLF;
        $expected .= '<option value="29" class="opt-29">29</option>'.Tags::CRLF;
        $expected .= '<option value="30" class="opt-30">30</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper hour"><select name="MFVARS[test_h]" id="test_h" data-selected="4" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1">TXT_DATETIME_HH</option>'.Tags::CRLF;
        $expected .= '<option value="0" class="opt-0">00</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4" selected="selected">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper minute"><select name="MFVARS[test_i]" id="test_i" data-selected="20" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1">TXT_DATETIME_II</option>'.Tags::CRLF;
        $expected .= '<option value="0" class="opt-0">00</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20" selected="selected">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '<option value="24" class="opt-24">24</option>'.Tags::CRLF;
        $expected .= '<option value="25" class="opt-25">25</option>'.Tags::CRLF;
        $expected .= '<option value="26" class="opt-26">26</option>'.Tags::CRLF;
        $expected .= '<option value="27" class="opt-27">27</option>'.Tags::CRLF;
        $expected .= '<option value="28" class="opt-28">28</option>'.Tags::CRLF;
        $expected .= '<option value="29" class="opt-29">29</option>'.Tags::CRLF;
        $expected .= '<option value="30" class="opt-30">30</option>'.Tags::CRLF;
        $expected .= '<option value="31" class="opt-31">31</option>'.Tags::CRLF;
        $expected .= '<option value="32" class="opt-32">32</option>'.Tags::CRLF;
        $expected .= '<option value="33" class="opt-33">33</option>'.Tags::CRLF;
        $expected .= '<option value="34" class="opt-34">34</option>'.Tags::CRLF;
        $expected .= '<option value="35" class="opt-35">35</option>'.Tags::CRLF;
        $expected .= '<option value="36" class="opt-36">36</option>'.Tags::CRLF;
        $expected .= '<option value="37" class="opt-37">37</option>'.Tags::CRLF;
        $expected .= '<option value="38" class="opt-38">38</option>'.Tags::CRLF;
        $expected .= '<option value="39" class="opt-39">39</option>'.Tags::CRLF;
        $expected .= '<option value="40" class="opt-40">40</option>'.Tags::CRLF;
        $expected .= '<option value="41" class="opt-41">41</option>'.Tags::CRLF;
        $expected .= '<option value="42" class="opt-42">42</option>'.Tags::CRLF;
        $expected .= '<option value="43" class="opt-43">43</option>'.Tags::CRLF;
        $expected .= '<option value="44" class="opt-44">44</option>'.Tags::CRLF;
        $expected .= '<option value="45" class="opt-45">45</option>'.Tags::CRLF;
        $expected .= '<option value="46" class="opt-46">46</option>'.Tags::CRLF;
        $expected .= '<option value="47" class="opt-47">47</option>'.Tags::CRLF;
        $expected .= '<option value="48" class="opt-48">48</option>'.Tags::CRLF;
        $expected .= '<option value="49" class="opt-49">49</option>'.Tags::CRLF;
        $expected .= '<option value="50" class="opt-50">50</option>'.Tags::CRLF;
        $expected .= '<option value="51" class="opt-51">51</option>'.Tags::CRLF;
        $expected .= '<option value="52" class="opt-52">52</option>'.Tags::CRLF;
        $expected .= '<option value="53" class="opt-53">53</option>'.Tags::CRLF;
        $expected .= '<option value="54" class="opt-54">54</option>'.Tags::CRLF;
        $expected .= '<option value="55" class="opt-55">55</option>'.Tags::CRLF;
        $expected .= '<option value="56" class="opt-56">56</option>'.Tags::CRLF;
        $expected .= '<option value="57" class="opt-57">57</option>'.Tags::CRLF;
        $expected .= '<option value="58" class="opt-58">58</option>'.Tags::CRLF;
        $expected .= '<option value="59" class="opt-59">59</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<div class="select-wrapper second"><select name="MFVARS[test_s]" id="test_s" data-selected="0" class="testclass">'.Tags::CRLF;
        $expected .= '<option value="-1" class="opt--1">TXT_DATETIME_SS</option>'.Tags::CRLF;
        $expected .= '<option value="0" class="opt-0" selected="selected">00</option>'.Tags::CRLF;
        $expected .= '<option value="1" class="opt-1">01</option>'.Tags::CRLF;
        $expected .= '<option value="2" class="opt-2">02</option>'.Tags::CRLF;
        $expected .= '<option value="3" class="opt-3">03</option>'.Tags::CRLF;
        $expected .= '<option value="4" class="opt-4">04</option>'.Tags::CRLF;
        $expected .= '<option value="5" class="opt-5">05</option>'.Tags::CRLF;
        $expected .= '<option value="6" class="opt-6">06</option>'.Tags::CRLF;
        $expected .= '<option value="7" class="opt-7">07</option>'.Tags::CRLF;
        $expected .= '<option value="8" class="opt-8">08</option>'.Tags::CRLF;
        $expected .= '<option value="9" class="opt-9">09</option>'.Tags::CRLF;
        $expected .= '<option value="10" class="opt-10">10</option>'.Tags::CRLF;
        $expected .= '<option value="11" class="opt-11">11</option>'.Tags::CRLF;
        $expected .= '<option value="12" class="opt-12">12</option>'.Tags::CRLF;
        $expected .= '<option value="13" class="opt-13">13</option>'.Tags::CRLF;
        $expected .= '<option value="14" class="opt-14">14</option>'.Tags::CRLF;
        $expected .= '<option value="15" class="opt-15">15</option>'.Tags::CRLF;
        $expected .= '<option value="16" class="opt-16">16</option>'.Tags::CRLF;
        $expected .= '<option value="17" class="opt-17">17</option>'.Tags::CRLF;
        $expected .= '<option value="18" class="opt-18">18</option>'.Tags::CRLF;
        $expected .= '<option value="19" class="opt-19">19</option>'.Tags::CRLF;
        $expected .= '<option value="20" class="opt-20">20</option>'.Tags::CRLF;
        $expected .= '<option value="21" class="opt-21">21</option>'.Tags::CRLF;
        $expected .= '<option value="22" class="opt-22">22</option>'.Tags::CRLF;
        $expected .= '<option value="23" class="opt-23">23</option>'.Tags::CRLF;
        $expected .= '<option value="24" class="opt-24">24</option>'.Tags::CRLF;
        $expected .= '<option value="25" class="opt-25">25</option>'.Tags::CRLF;
        $expected .= '<option value="26" class="opt-26">26</option>'.Tags::CRLF;
        $expected .= '<option value="27" class="opt-27">27</option>'.Tags::CRLF;
        $expected .= '<option value="28" class="opt-28">28</option>'.Tags::CRLF;
        $expected .= '<option value="29" class="opt-29">29</option>'.Tags::CRLF;
        $expected .= '<option value="30" class="opt-30">30</option>'.Tags::CRLF;
        $expected .= '<option value="31" class="opt-31">31</option>'.Tags::CRLF;
        $expected .= '<option value="32" class="opt-32">32</option>'.Tags::CRLF;
        $expected .= '<option value="33" class="opt-33">33</option>'.Tags::CRLF;
        $expected .= '<option value="34" class="opt-34">34</option>'.Tags::CRLF;
        $expected .= '<option value="35" class="opt-35">35</option>'.Tags::CRLF;
        $expected .= '<option value="36" class="opt-36">36</option>'.Tags::CRLF;
        $expected .= '<option value="37" class="opt-37">37</option>'.Tags::CRLF;
        $expected .= '<option value="38" class="opt-38">38</option>'.Tags::CRLF;
        $expected .= '<option value="39" class="opt-39">39</option>'.Tags::CRLF;
        $expected .= '<option value="40" class="opt-40">40</option>'.Tags::CRLF;
        $expected .= '<option value="41" class="opt-41">41</option>'.Tags::CRLF;
        $expected .= '<option value="42" class="opt-42">42</option>'.Tags::CRLF;
        $expected .= '<option value="43" class="opt-43">43</option>'.Tags::CRLF;
        $expected .= '<option value="44" class="opt-44">44</option>'.Tags::CRLF;
        $expected .= '<option value="45" class="opt-45">45</option>'.Tags::CRLF;
        $expected .= '<option value="46" class="opt-46">46</option>'.Tags::CRLF;
        $expected .= '<option value="47" class="opt-47">47</option>'.Tags::CRLF;
        $expected .= '<option value="48" class="opt-48">48</option>'.Tags::CRLF;
        $expected .= '<option value="49" class="opt-49">49</option>'.Tags::CRLF;
        $expected .= '<option value="50" class="opt-50">50</option>'.Tags::CRLF;
        $expected .= '<option value="51" class="opt-51">51</option>'.Tags::CRLF;
        $expected .= '<option value="52" class="opt-52">52</option>'.Tags::CRLF;
        $expected .= '<option value="53" class="opt-53">53</option>'.Tags::CRLF;
        $expected .= '<option value="54" class="opt-54">54</option>'.Tags::CRLF;
        $expected .= '<option value="55" class="opt-55">55</option>'.Tags::CRLF;
        $expected .= '<option value="56" class="opt-56">56</option>'.Tags::CRLF;
        $expected .= '<option value="57" class="opt-57">57</option>'.Tags::CRLF;
        $expected .= '<option value="58" class="opt-58">58</option>'.Tags::CRLF;
        $expected .= '<option value="59" class="opt-59">59</option>'.Tags::CRLF;
        $expected .= '</select></div>';
        $expected .= '<span class="timestamp-reset" title="TXT_PANEL_DATA_FORM_TIMESTAMP_CONTROLL_RESET"/></div>';

        $this->assertEquals($expected, DateAndTime::selectTimestamp('test', ['y' => 1978, 'm' => 4, 'd' => 15, 'h' => 4, 'i' => 20, 's' => 0], ['class' => 'testclass']));
        $this->assertEquals($expected, DateAndTime::selectTimestamp('test', mktime(4, 20, 0, 4, 15, 1978), ['class' => 'testclass']));
    }
}
